#ifndef ARKCHEMY_CAFEOS_GX2_NAMES_H
#define ARKCHEMY_CAFEOS_GX2_NAMES_H

/* Generated from cafeos_gx2.h. Index matches the argument each
   ppc_import_gx2_* shim passes to ark_gx2_note, so GX2CENSUS can print names
   instead of addresses.

   The first census keyed on call-site lr with 24 slots, which filled with the
   first sites seen and dropped every hot one -- 133,069 calls with only ~110
   attributed. Keying on the function itself bounds the table at the number of
   shims and makes every entry meaningful. */

#define ARKCHEMY_GX2_NAME_COUNT 140

static const char *const g_arkchemy_gx2_names[ARKCHEMY_GX2_NAME_COUNT] = {
    "GX2Init",
    "GX2Shutdown",
    "GX2SetViewport",
    "GX2SetScissor",
    "GX2SetLineWidth",
    "GX2SetPointSize",
    "GX2SetPolygonOffset",
    "GX2SetBlendConstantColor",
    "GX2SetBlendControl",
    "GX2SetColorControl",
    "GX2SetAlphaTest",
    "GX2SetAlphaToMask",
    "GX2SetDepthStencilControl",
    "GX2SetPolygonControl",
    "GX2SetCullOnlyControl",
    "GX2SetRasterizerClipControl",
    "GX2SetDepthOnlyControl",
    "GX2SetStencilMask",
    "GX2SetTargetChannelMasks",
    "GX2SetPrimitiveRestartIndex",
    "GX2ClearColor",
    "GX2SwapScanBuffers",
    "GX2Flush",
    "GX2DrawDone",
    "GX2WaitForVsync",
    "GX2GetLastSubmittedTimeStamp",
    "GX2GetRetiredTimeStamp",
    "GX2WaitTimeStamp",
    "GX2GetSwapStatus",
    "GX2SetEventCallback",
    "GX2SetPixelSampler",
    "GX2SetVertexSampler",
    "GX2SetPixelSamplerBorderColor",
    "GX2SetVertexSamplerBorderColor",
    "GX2SetColorBuffer",
    "GX2SetDepthBuffer",
    "GX2SetPixelTexture",
    "GX2SetVertexTexture",
    "GX2CopyColorBufferToScanBuffer",
    "GX2Init",
    "GX2Shutdown",
    "GX2SetViewport",
    "GX2SetScissor",
    "GX2SetLineWidth",
    "GX2SetPointSize",
    "GX2SetPolygonOffset",
    "GX2SetBlendConstantColor",
    "GX2SetBlendControl",
    "GX2SetColorControl",
    "GX2SetAlphaTest",
    "GX2SetAlphaToMask",
    "GX2SetDepthStencilControl",
    "GX2SetPolygonControl",
    "GX2SetCullOnlyControl",
    "GX2SetRasterizerClipControl",
    "GX2SetDepthOnlyControl",
    "GX2SetStencilMask",
    "GX2SetTargetChannelMasks",
    "GX2SetPrimitiveRestartIndex",
    "GX2ClearColor",
    "GX2SwapScanBuffers",
    "GX2Flush",
    "GX2DrawDone",
    "GX2WaitForVsync",
    "GX2GetLastSubmittedTimeStamp",
    "GX2GetRetiredTimeStamp",
    "GX2WaitTimeStamp",
    "GX2GetSwapStatus",
    "GX2SetEventCallback",
    "GX2SetPixelSampler",
    "GX2SetVertexSampler",
    "GX2SetPixelSamplerBorderColor",
    "GX2SetVertexSamplerBorderColor",
    "GX2SetColorBuffer",
    "GX2SetDepthBuffer",
    "GX2SetPixelTexture",
    "GX2SetVertexTexture",
    "GX2CopyColorBufferToScanBuffer",
    "GX2TempGetGPUVersion",
    "GX2GetSystemTVScanMode",
    "GX2GetSystemTVAspectRatio",
    "GX2SetSwapInterval",
    "GX2SetTVEnable",
    "GX2SetDRCEnable",
    "GX2SetTVScale",
    "GX2SetDRCScale",
    "GX2SetTVGamma",
    "GX2SetDRCGamma",
    "GX2SetTVBuffer",
    "GX2SetDRCBuffer",
    "GX2Invalidate",
    "GX2SetPointLimits",
    "GX2SetStreamOutEnable",
    "GX2SetTessellation",
    "GX2SetMinTessellationLevel",
    "GX2SetMaxTessellationLevel",
    "GX2GetDisplayListWriteStatus",
    "GX2GetSurfaceFormatBits",
    "GX2CalcDepthBufferHiZInfo",
    "GX2CalcColorBufferAuxInfo",
    "GX2CalcSurfaceSizeAndAlignment",
    "GX2SetClearDepth",
    "GX2SetClearStencil",
    "GX2SetClearDepthStencil",
    "GX2ClearDepthStencilEx",
    "GX2InitSampler",
    "GX2InitSamplerXYFilter",
    "GX2InitSamplerZMFilter",
    "GX2InitSamplerLOD",
    "GX2InitSamplerClamping",
    "GX2InitSamplerBorderType",
    "GX2InitSamplerDepthCompare",
    "GX2InitColorBufferRegs",
    "GX2InitDepthBufferRegs",
    "GX2InitDepthBufferHiZEnable",
    "GX2InitTextureRegs",
    "GX2SetupContextStateEx",
    "GX2SetContextState",
    "GX2CopySurface",
    "GX2CalcTVSize",
    "GX2CalcDRCSize",
    "GX2BeginDisplayListEx",
    "GX2EndDisplayList",
    "GX2CopyDisplayList",
    "GX2DirectCallDisplayList",
    "GX2ResolveAAColorBuffer",
    "GX2ExpandAAColorBuffer",
    "GX2ExpandDepthBuffer",
    "GX2ConvertDepthBufferToTextureSurface",
    "GX2SetAttribBuffer",
    "GX2SetFetchShader",
    "GX2SetVertexShader",
    "GX2SetPixelShader",
    "GX2SetPixelUniformReg",
    "GX2SetVertexUniformReg",
    "GX2SetShaderModeEx",
    "GX2CalcFetchShaderSizeEx",
    "GX2InitFetchShaderEx",
    "GX2DrawEx",
    "GX2DrawIndexedEx",
};

#endif /* ARKCHEMY_CAFEOS_GX2_NAMES_H */
