#!/usr/bin/env python3
"""Write the names a guest function must not have, for src/main.cpp.

Every guest function becomes `ppc_<name>` in generated C, in the same
translation unit as the runtime headers. A guest function whose name makes
that collide with a runtime identifier breaks the build -- a function named
`dispatch` becomes a second `ppc_dispatch` -- or, worse, compiles and calls
the wrong thing. This collects every `ppc_*` identifier in include/ (code
only, comments stripped) so recomp can rename such functions. It runs at
build time, so the set cannot drift from the headers.

Usage: gen_reserved_names.py <include dir> <output .inc>
"""
import pathlib
import re
import sys

inc, out = pathlib.Path(sys.argv[1]), pathlib.Path(sys.argv[2])
names = set()
for f in sorted(list(inc.glob("*.h")) + list(inc.glob("*.c"))):
    src = f.read_text(encoding="utf-8", errors="replace")
    src = re.sub(r"/\*.*?\*/", " ", src, flags=re.S)
    src = re.sub(r"//[^\n]*", " ", src)
    names.update(m[4:] for m in re.findall(r"\bppc_[A-Za-z0-9_]+", src))
# emitted by recomp itself, whether or not a header mentions them
names.update(["dispatch", "init_globals", "run_static_initializers"])
out.parent.mkdir(parents=True, exist_ok=True)
text = "// generated by tools/gen_reserved_names.py -- do not edit\n" + \
       "".join('"%s",\n' % n for n in sorted(n for n in names if n))
if not out.exists() or out.read_text() != text:
    out.write_text(text)
