#include <fstream>
#include <iostream>
#include <map>
#include <sstream>

#include "codegen.h"
#include "disassembler.h"
#include "elf_loader.h"
#include "func_recovery.h"

int main(int argc, char **argv) {
    std::vector<std::string> args(argv + 1, argv + argc);
    bool force_stripped = false;
    std::string input_path, output_path, entry_alias;
    for (size_t i = 0; i < args.size(); i++) {
        if (args[i] == "--stripped") {
            force_stripped = true;
        } else if (args[i] == "-o" && i + 1 < args.size()) {
            output_path = args[++i];
        } else if (args[i] == "--entry-alias" && i + 1 < args.size()) {
            entry_alias = args[++i];
        } else if (input_path.empty()) {
            input_path = args[i];
        }
    }
    if (input_path.empty() || output_path.empty()) {
        std::cerr << "usage: recomp [--stripped] [--entry-alias NAME] <input.elf> -o <output.c>\n";
        std::cerr << "  --stripped:          ignore any symbol table and recover function\n";
        std::cerr << "                       boundaries via control-flow analysis instead\n";
        std::cerr << "                       (see func_recovery.h)\n";
        std::cerr << "  --entry-alias NAME:  rename whichever function starts at the ELF\n";
        std::cerr << "                       entry point to NAME -- heuristic recovery names\n";
        std::cerr << "                       functions after their address, which shifts if\n";
        std::cerr << "                       the binary is relinked; callers of the generated\n";
        std::cerr << "                       C that want a stable entry symbol should use this\n";
        return 1;
    }

    recomp::ElfImage img;
    std::string err;
    if (!recomp::load_elf(input_path, img, err)) {
        std::cerr << "error: " << err << "\n";
        return 1;
    }
    recomp::assign_global_addrs(img);

    if (force_stripped || img.functions.empty()) {
        img.functions = recomp::recover_functions_heuristic(img.text, img.text_addr, img.entry, err);
        if (img.functions.empty()) {
            std::cerr << "error: heuristic function recovery found nothing: " << err << "\n";
            return 1;
        }
        std::cerr << "no usable symbol table -- recovered " << img.functions.size()
                   << " function(s) via control-flow analysis\n";
    }

    if (!entry_alias.empty()) {
        for (auto &fn : img.functions) {
            if (fn.addr == img.entry) fn.name = entry_alias;
        }
    }

    std::map<uint32_t, std::string> addr_to_name;
    for (const auto &fn : img.functions) addr_to_name[fn.addr] = fn.name;

    std::ostringstream body;
    int unhandled_total = 0;

    for (const auto &fn : img.functions) {
        uint32_t start_off = fn.addr - img.text_addr;
        if (start_off + fn.size > img.text.size()) {
            std::cerr << "error: function '" << fn.name << "' extends past .text\n";
            return 1;
        }

        recomp::DisasmResult insns;
        if (!recomp::disassemble_range(&img.text[start_off], fn.size, fn.addr, insns, err)) {
            std::cerr << "error: disassembling '" << fn.name << "': " << err << "\n";
            return 1;
        }

        auto unhandled = recomp::generate_function_c(img, fn, insns, addr_to_name, body);
        unhandled_total += (int)unhandled.size();
        std::cerr << "recompiled " << fn.name << " (" << insns.size() << " instructions, " << unhandled.size()
                   << " unhandled)\n";
    }

    std::ofstream out(output_path);
    if (!out) {
        std::cerr << "error: cannot write '" << output_path << "'\n";
        return 1;
    }
    out << "/* Generated by Bramble's recomp tool. Do not edit by hand. */\n";
    out << "#include \"ppc_runtime.h\"\n\n";
    for (const auto &fn : img.functions) {
        out << "void ppc_" << fn.name << "(PpcContext *ctx);\n";
    }
    out << "void ppc_dispatch(PpcContext *ctx, uint32_t addr);\n";
    out << "\n";

    // Global/static variables (.data/.bss) live at synthetic addresses in
    // ctx->mem (see ElfImage::global_section_base) -- .data's initial
    // content has to actually be copied in before any recompiled function
    // runs, the same job a real ELF loader does. Callers must invoke this
    // once before calling any ppc_<function>.
    out << "void ppc_init_globals(PpcContext *ctx) {\n";
    for (const auto &entry : img.global_section_base) {
        auto bytes_it = img.section_bytes.find(entry.first);
        if (bytes_it == img.section_bytes.end()) continue; // e.g. .bss: no file content, mem is already zeroed
        const std::vector<uint8_t> &bytes = bytes_it->second;
        for (size_t i = 0; i < bytes.size(); i++) {
            if (bytes[i] == 0) continue; // ctx->mem starts zeroed; skip no-op stores
            out << "  ppc_store_u8(ctx, " << (entry.second + (uint32_t)i) << "u, " << (unsigned)bytes[i] << ");\n";
        }
    }
    out << "}\n\n";

    // Indirect-call dispatch table (mtctr/bctrl -- function pointers,
    // vtables, callback tables): the target address is only known at
    // runtime, so it can't be resolved to a direct C call the way `bl` is.
    // Function addresses live in the same address space as ElfFunction::addr
    // (relocatable-object .text offsets, or real linked addresses), so a
    // plain switch over that address is enough to route to the matching
    // generated function.
    out << "void ppc_dispatch(PpcContext *ctx, uint32_t addr) {\n";
    out << "  switch (addr) {\n";
    for (const auto &fn : img.functions) {
        out << "    case " << fn.addr << "u: ppc_" << fn.name << "(ctx); return;\n";
    }
    out << "  }\n";
    out << "}\n\n";

    out << body.str();

    if (unhandled_total > 0) {
        std::cerr << unhandled_total << " unhandled instruction(s) -- generated code will not compile.\n";
        return 2;
    }

    std::cerr << "wrote " << output_path << " (" << img.functions.size() << " function(s))\n";
    return 0;
}
